services:
  xserver:
    image: devrt/xserver
    ipc: host
    security_opt:
      - seccomp:unconfined
    environment:
      - DISPLAY=:9
    ports:
      - "3000:80"

  ros-master:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    ipc: host
    volumes:
      - ./src/:/dinamos_ws/src/:rw
      - ./Makefile:/dinamos_ws/Makefile:rw

    depends_on:
      - xserver
    volumes_from:
      - xserver
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
      - DISPLAY=:9
      - ROS_DOMAIN_ID=30
      - LDS_MODEL=LDS-02
    command:
      - /bin/bash
      - -c
      - |
        source /opt/ros/humble/setup.bash &&
        colcon build --symlink-install &&
        source install/setup.bash &&
        xterm -hold -T Terminal -e "tmux"
